local color_utils = require('tavern.util.colors')
local M = {}

local colors = {
    -- Shades and Tints
    base00 = '#1b1413', -- Background
    base01 = '#41302e',
    base02 = '#58413f',
    base03 = '#6f524f',
    base04 = '#bba2a0',
    base05 = '#cbb8b7', -- Foreground
    base06 = '#dccfcd',
    base07 = '#ece5e4',
    -- Colors
    base08 = '#CC8051',
    base09 = '#C79C0B',
    base0A = '#D1C624',
    base0B = '#53B835',
    base0C = '#AEB848',
    base0D = '#6683D6',
    base0E = '#A37B41',
    base0F = '#B3A532',
    -- base08 = '#cb6077',
    -- base09 = '#c58920',
    -- base0A = '#e8e80e',
    -- base0B = '#05b876',
    -- base0C = '#8ab3b5',
    -- base0D = '#5a86d3',
    -- base0E = '#a34d5f',
    -- base0F = '#b0987a',
}

local theme = {
    ColorColumn = { bg = color_utils.lighten(colors.base00, 0.15) },
    Cursor = { fg = color_utils.invert_color(colors.base05), bg = colors.base05 },
    CursorColumn = { bg = color_utils.lighten(colors.base00, 0.15) },
    CursorLine = { link = 'CursorColumn' },
    Directory = { fg = colors.base0F, style = { 'bold' } },
    DiffAdd = { bg = colors.base0B, fg = colors.base07 },
    DiffChange = { bg = color_utils.darken(colors.base0E, 0.3), fg = colors.base07 },
    DiffDelete = { bg = colors.base08, fg = colors.base07 },
    DiffText = { bg = colors.base0D, fg = colors.base07 },
    EndOfBuffer = { fg = color_utils.darken(colors.base05, 0.3) },
    ErrorMsg = { fg = color_utils.saturate(colors.base0E, 0.2) },
    VertSplit = { bg = colors.base00, fg = colors.base05 },
    Folded = { bg = colors.base03, fg = colors.base05 },
    FoldColumn = { link = 'Folded' },
    SignColumn = { bg = colors.base00 },
    IncSearch = { bg = colors.base0A, fg = colors.base00 },
    Substitute = { link = 'IncSearch' },
    LineNr = { fg = color_utils.lighten(colors.base01, 0.3) },
    CursorLineNr = { fg = colors.base09 },
    MatchParen = { bg = colors.base03 },
    ModeMsg = { bg = colors.base00, fg = colors.base05, style = { 'bold' } },
    NonText = { fg = color_utils.darken(colors.base05, 0.3) },
    Normal = { bg = colors.base00, fg = colors.base05 },
    NormalFloat = { bg = color_utils.darken(colors.base00, 0.1), fg = colors.base05 },
    NormalNC = { link = 'Normal' },
    Pmenu = { bg = color_utils.lighten(colors.base00, 0.1), fg = colors.base05 },
    PmenuSel = { bg = color_utils.lighten(colors.base00, 0.25), style = { 'bold' } },
    PmenuSbar = { bg = colors.base02 },
    PmenuThumb = { bg = colors.base05 },
    Question = { fg = colors.base05, style = { 'italic' } },
    QuickFixLine = { fg = colors.base0A },
    Search = { link = 'IncSearch' },
    SpecialKey = { fg = colors.base0E },
    SpellBad = { fg = colors.base0E, style = { 'underline', 'italic' } },
    SpellCap = { fg = colors.base0D, style = { 'italic' } },
    SpellLocal = { fg = colors.base0F },
    SpellRare = { fg = colors.base09 },
    StatusLine = { bg = colors.base02 },
    StatusLineNC = { bg = colors.base01 },
    TabLine = { bg = colors.base01 },
    TabLineFill = { bg = colors.base01 },
    TabLineSel = { bg = colors.base00, style = { 'bold' } },
    Title = { fg = colors.base05, style = { 'bold' } },
    Visual = { bg = color_utils.darken(colors.base02, 0.2), style = { 'bold' } },
    VisualNOS = { bg = color_utils.darken(colors.base02, 0.3) },
    WarningMsg = { fg = colors.base0A, style = { 'bold', 'italic' } },
    Whitespace = { fg = color_utils.lighten(color_utils.desaturate(colors.base00, 0.25), 0.25) },
    Winseparator = { link = 'Normal' },
    WildMenu = { bg = colors.base01, fg = colors.base05 },
    Comment = { fg = color_utils.desaturate(colors.base03, 0.15), style = { 'italic' } },
    Constant = { fg = colors.base09 },
    String = { fg = colors.base0B },
    Character = { fg = colors.base0B },
    Number = { fg = colors.base09 },
    Boolean = { fg = colors.base09 },
    Float = { fg = colors.base09 },
    Identifier = { fg = colors.base08 },
    Function = { fg = colors.base0A },
    Statement = { fg = colors.base09 },
    Conditional = { fg = colors.base0E },
    Repeat = { fg = colors.base0E },
    Label = { fg = colors.base0E },
    Operator = { fg = colors.base09 },
    Keyword = { fg = colors.base0E },
    Exception = { fg = colors.base0E },
    PreProc = { fg = colors.base09 },
    Include = { fg = colors.base09 },
    Define = { fg = colors.base09 },
    Macro = { fg = colors.base0C },
    PreCondit = { fg = colors.base09 },
    Type = { fg = colors.base0D },
    StorageClass = { fg = colors.base0E },
    Structure = { fg = colors.base0D },
    Typedef = { fg = colors.base0D },
    Special = { fg = colors.base0C },
    SpecialChar = { fg = colors.base0C },
    SpecialComment = { fg = colors.base0C },
    Tag = { fg = colors.base09 },
    Delimiter = { fg = colors.base09 },
    Debug = { fg = colors.base09 },
    DiagnosticError = { link = 'ErrorMsg' },
    DiagnosticWarn = { fg = colors.base0A },
    DiagnosticInfo = { fg = colors.base0C },
    DiagnosticHint = { fg = colors.base0B },
    -- Gitsigns
    GitSignsAdd = { bg = colors.base00, fg = colors.base09 },
    GitSignsChange = { bg = colors.base00, fg = colors.base0A },
    GitSignsDelete = { bg = colors.base00, fg = colors.base08 },
    -- Lazy.nvim
    LazyProp = { fg = colors.base0E },
    LazyDimmed = { fg = color_utils.darken(colors.base04, 0.25) },
    -- Notify.nvim
    NotifyBackground = { link = 'Normal' },
}

function M.get_theme()
    return theme
end

return M
